// <auto-generated />
namespace CMS_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _17081 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17081));
        
        string IMigrationMetadata.Id
        {
            get { return "201608171209425_17081"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
