// <auto-generated />
namespace CMS_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class perfreport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perfreport));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131048468_perfreport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
